# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: bun run zip
    - name: Release
      uses: softprops/action-gh-release@v2
      draft: true
      with:
        files: easy-school-registration.zip
